#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pydio"
name = "Pydio"
description.en = "File sharing platform"
description.fr = "Plateforme de partage de fichiers"

version = "4.4.17~ynh1"

maintainers = ["julienmalik"]

[upstream]
license = "AGPL-3.0"
website = "https://pydio.com"
admindoc = "https://pydio.com/en/docs"
code = "https://github.com/pydio/cells"
cpe = "cpe:2.3:a:pydio:cells"
fund = "https://pydio.com/en/pricing"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]
    [resources.sources.main]
    amd64.url = "https://download.pydio.com/pub/cells/release/4.4.17/linux-amd64/pydio-cells-4.4.17-linux-amd64.zip"
    amd64.sha256 = "94cd5ce5f99bdb44d5f8a9862f8d4273c5a8d7228b3eb658def7d8a5bb035da0"
    arm64.url = "https://download.pydio.com/pub/cells/release/4.4.17/linux-arm64/pydio-cells-4.4.17-linux-arm64.zip"
    arm64.sha256 = "abbc2444c3069e7309289b58bd888d0cddcac9b44a4f7702846ed80748c8deb1"
    armhf.url = "https://download.pydio.com/pub/cells/release/4.4.17/linux-arm/pydio-cells-4.4.17-linux-arm.zip"
    armhf.sha256 = "53adfa3a7992e8054f97b2df58359c1630025c7f436fe29d2209025048d8db6f"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8080
    discovery_grpc.default = 50051
    grpc.default = 50053

    [resources.apt]
    packages = [
        "acl",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
