packaging_format = 2

id = "pydio"
name = "Pydio"
description.en = "File sharing platform"
description.fr = "Plateforme de partage de fichiers"

version = "4.2.5~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "AGPL-3.0"
website = "https://pydio.com"
admindoc = "https://pydio.com/en/docs"
code = "https://github.com/pydio/cells"
cpe = "cpe:2.3:a:pydio:cells"
fund = "https://pydio.com/en/pricing"

[integration]
yunohost = ">= 11.1.21"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        amd64.url = "https://download.pydio.com/pub/cells/release/4.2.5/linux-amd64/pydio-cells-4.2.5-linux-amd64.zip"
        amd64.sha256 = "75467de7b763ed163f3b1956a9b32bcaece52a056979763dcfe315bd2c7273db"

        armhf.url = "https://download.pydio.com/pub/cells/release/4.2.5/linux-arm/pydio-cells-4.2.5-linux-arm.zip"
        armhf.sha256 = "b81ea76619b3d6593147014094e80fa5d659b64cc197d826236daea5d8da7baa"

        arm64.url = "https://download.pydio.com/pub/cells/release/4.2.5/linux-arm64/pydio-cells-4.2.5-linux-arm64.zip"
        arm64.sha256 = "068d3d7a32f3d9fd87f6ccede4b4721b9e4530234269f9a638fc630da17150ba"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    group = "www-data:rwx"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8080
    discovery_grpc.default = 50051
    grpc.default = 50052

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
