#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pydio"
name = "Pydio"
description.en = "File sharing platform"
description.fr = "Plateforme de partage de fichiers"

version = "4.4.13~ynh1"

maintainers = ["julienmalik"]

[upstream]
license = "AGPL-3.0"
website = "https://pydio.com"
admindoc = "https://pydio.com/en/docs"
code = "https://github.com/pydio/cells"
cpe = "cpe:2.3:a:pydio:cells"
fund = "https://pydio.com/en/pricing"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "700M"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]
    [resources.sources.main]
    amd64.url = "https://download.pydio.com/pub/cells/release/4.4.13/linux-amd64/pydio-cells-4.4.13-linux-amd64.zip"
    amd64.sha256 = "bfaccab28c6605e3b63801b94c5dd3ac0bf517080289e7e12e441d648964addc"
    arm64.url = "https://download.pydio.com/pub/cells/release/4.4.13/linux-arm64/pydio-cells-4.4.13-linux-arm64.zip"
    arm64.sha256 = "59c4a7a726c6dfb1d579abe3a7fd4e09bc3aa6ec28ff8a7c76ac893721d22af6"
    armhf.url = "https://download.pydio.com/pub/cells/release/4.4.13/linux-arm/pydio-cells-4.4.13-linux-arm.zip"
    armhf.sha256 = "ebbd4758fe9539ccc0ae81b61580fbb1b2a6e066a321255ba3b7fa4e8b990374"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    group = "www-data:rwx"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8080
    discovery_grpc.default = 50051
    grpc.default = 50053

    [resources.apt]
    packages = [
        "acl",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
