#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pydio"
name = "Pydio"
description.en = "File sharing platform"
description.fr = "Plateforme de partage de fichiers"

version = "3.0.9~ynh2"

maintainers = ["julienmalik"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://pydio.com"
admindoc = "https://pydio.com/en/docs/"
code = "https://github.com/pydio/cells"
cpe = "cpe:2.3:a:pydio:cells"
fund = "https://pydio.com/en/pricing"

[integration]
yunohost = ">= 11.1.21"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://download.pydio.com/pub/cells/release/3.0.9/linux-amd64/pydio-cells-3.0.9-linux-amd64.zip"
    sha256 = "54b1f92dcaa0204f0b2e6ebb1daff0d4911d0b1c60d68acacfeb6290170dd4a8"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    group = "www-data:rwx"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 8080

    [resources.apt]
    packages = [
        "acl",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
