test_format = 1.0

[default]

    # The test IDs to be used in only/exclude statements are: install.root, install.subdir,
    # install.nourl, install.multi, backup_restore, upgrade, upgrade.someCommitId change_url
    exclude = ["install.subdir", "install.nourl", "change_url"]

    # test_upgrade_from.00a1a6e7.name = "Upgrade from 5.4"
    # test_upgrade_from.00a1a6e7.args.foo = "bar"
