#!/bin/bash

sudo rm -rf /var/www/pydio
sudo rm -rf /home/yunohost.app/pydio

domain=$(sudo yunohost app setting pydio domain)
sudo rm -f /etc/nginx/conf.d/$domain.d/pydio.conf
sudo rm -f /etc/php5/fpm/pool.d/pydio.conf
sudo rm -f /etc/php5/fpm/conf.d/20-pydio.ini

# Trash db
db_user=pydio
db_name=pydio
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

for i in $(ls /home)
do
    sudo yunohost user list --json | grep -q "\"username\": \"$i\""
    if [[ $? -eq 0 ]];
    then
        sudo setfacl -x g:pydio:rwx /home/$i
    fi
done

sudo userdel pydio > /dev/null 2>&1

sudo service nginx reload
sudo service php5-fpm restart