#!/bin/bash

# Removing executable files
sudo rm -rf /var/www/pydio
domain=$(sudo yunohost app setting pydio domain)
sudo rm -f /etc/nginx/conf.d/$domain.d/pydio.conf

# Trash db
db_user=pydio
db_name=pydio
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

# Restarting services
sudo service nginx reload
